<a href="https://colab.research.google.com/github/MdRufsan/Python-/blob/main/pandas/3_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas হলো Python লাইব্রেরি যা টেবিলভিত্তিক ডেটা (CSV, Excel, SQL) পড়া, পরিষ্কার করা, বিশ্লেষণ করা এবং পরিবর্তন করার জন্য ব্যবহৃত হয়।

Series কি?
Series হলো এক কলামের ডেটা (NumPy array + লেবেল)।
এটা মূলত 1D labeled array।

In [ ]:
import pandas as pd

data = [10, 20, 30, 40]
s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

 DataFrame কি?
DataFrame হলো একটি টেবিল – অনেকগুলো column + row থাকে।
এটা হলো 2D table structure (Excel এর মতো)।

In [ ]:
import pandas as pd
data = {
    'Name': ['Shanto', 'Arif', 'Nadia'],
    'Age': [23, 25, 24],
    'Dept': ['SWE', 'EEE', 'BBA']
}

df=pd.DataFrame(data)

print(df)

     Name  Age Dept
0  Shanto   23  SWE
1    Arif   25  EEE
2   Nadia   24  BBA

In [ ]:
# Column ও Row Access
import pandas as pd
print(df['Name'])      # শুধুমাত্র Name কলাম
print("..............................")
print(df['Age'])
print("..............................")

print(df.loc[0])       # index দিয়ে row
print('...............................')
print(df.iloc[1])      # position দিয়ে row

0    Shanto
1      Arif
2     Nadia
Name: Name, dtype: object
..............................
0    23
1    25
2    24
Name: Age, dtype: int64
..............................
Name    Shanto
Age         23
Dept       SWE
Name: 0, dtype: object
...............................
Name    Arif
Age       25
Dept     EEE
Name: 1, dtype: object

In [ ]:
#Pandas Basic Task Solution

import pandas as pd

#  DataFrame create
data = {
    'Name': ['Santo', 'Rafi', 'Nabila'],
    'Age': [26, 25, 24],
    'Subject': ['CSE', 'BBA', 'EEE']
}

df = pd.DataFrame(data)

#  full DataFrame
print("Full DataFrame:")
print(df)

# only name col
print("\nName column:")
print(df['Name'])

# 2nd students records (index=1)
print("\nSecond student (index 1):")
print(df.loc[1])

Full DataFrame:
     Name  Age Subject
0   Santo   26     CSE
1    Rafi   25     BBA
2  Nabila   24     EEE

Name column:
0     Santo
1      Rafi
2    Nabila
Name: Name, dtype: object

Second student (index 1):
Name       Rafi
Age          25
Subject     BBA
Name: 1, dtype: object

In [ ]:
import pandas as pd

# ডেটা তৈরি
data = {
    'Name': ['Santo', 'Rafi', 'Nabila', 'Asif', 'Tania'],
    'Age': [25, 24, 23, 22, 24],
    'Score': [85, 90, 88, 78, 92]
}

# DataFrame বানানো
df = pd.DataFrame(data)

# CSV ফাইলে লেখা
df.to_csv('students.csv', index=False)

print("students.csv ফাইল তৈরি হয়েছে!")

students.csv ফাইল তৈরি হয়েছে!

In [ ]:
import pandas as pd

# 1. CSV ফাইল পড়া
df = pd.read_csv('students.csv')
print (df)

     Name  Age  Score
0   Santo   25     85
1    Rafi   24     90
2  Nabila   23     88
3    Asif   22     78
4   Tania   24     92

In [ ]:
# 2. প্রথম ৫টি row দেখা by default
print(df.head())

     Name  Age  Score
0   Santo   25     85
1    Rafi   24     90
2  Nabila   23     88
3    Asif   22     78
4   Tania   24     92

In [ ]:
# 3. ডেটার ধরণ ও সারাংশ
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None

In [ ]:

# 4. পরিসংখ্যান
print(df.describe())

             Age      Score
count   5.000000   5.000000
mean   23.600000  86.600000
std     1.140175   5.458938
min    22.000000  78.000000
25%    23.000000  85.000000
50%    24.000000  88.000000
75%    24.000000  90.000000
max    25.000000  92.000000

**Selecting & Filtering in pandas**

In [ ]:
import pandas as pd

# ডেটা তৈরি
data = {
    'Name': ['Santo', 'Rafi', 'Nabila', 'Asif', 'Tania'],
    'Age': [25, 24, 23, 22, 24],
    'Score': [85, 90, 88, 78, 92]
}

# DataFrame বানানো
df = pd.DataFrame(data)

# CSV ফাইলে লেখা
df.to_csv('students.csv', index=False)

print("students.csv ফাইল তৈরি হয়েছে!")

students.csv ফাইল তৈরি হয়েছে!

In [ ]:
import pandas as pd

# students.csv ফাইল থেকে ডেটা রিড করা
df = pd.read_csv('students.csv')
df

     Name  Age  Score
0   Santo   25     85
1    Rafi   24     90
2  Nabila   23     88
3    Asif   22     78
4   Tania   24     92

In [ ]:
#  Column Select:

# শুধু Name কলাম
print(df['Name'])
print('................................')

# Name আর Score
print(df[['Name', 'Score']])

0     Santo
1      Rafi
2    Nabila
3      Asif
4     Tania
Name: Name, dtype: object
................................
     Name  Score
0   Santo     85
1    Rafi     90
2  Nabila     88
3    Asif     78
4   Tania     92

In [ ]:
#  Row Select:

# প্রথম row (label দিয়ে)
print(df.loc[0])

print('..............................')

# দ্বিতীয় row (position দিয়ে)
print(df.iloc[1])

Name     Santo
Age         25
Score       85
Name: 0, dtype: object
..............................
Name     Rafi
Age        24
Score      90
Name: 1, dtype: object

In [ ]:
# যাদের Score ৮৫-এর বেশি
high_scores = df[df['Score']>85]
print(high_scores)

print('..........................')

# Age ২৪ এবং তার বেশি
older_students = df[df['Age'] >= 24]
print(older_students)

print('.........................')

# Age ২৪ এবং score 90 তার বেশি
print(df[(df['Age'] >= 24) & (df['Score'] > 90)])

     Name  Age  Score
1    Rafi   24     90
2  Nabila   23     88
4   Tania   24     92
..........................
    Name  Age  Score
0  Santo   25     85
1   Rafi   24     90
4  Tania   24     92
.........................
    Name  Age  Score
4  Tania   24     92

**Data Cleaning with pandas**

ডেটাতে যেসব ভুল বা সমস্যা থাকে সেগুলো ঠিক করা — যেমন missing value, duplicate row, column type ইত্যাদি।

In [ ]:
import pandas as pd

# Raw data creation (missing value ও duplicate সহ)
data = {
    'Name': ['Shanto', 'Rafi', 'Nabila', 'Rafi'],
    'Age': [25, None, 23, None],
    'Score': [85, 90, None, 90]
}
df = pd.DataFrame(data)

display(df)

     Name   Age  Score
0  Shanto  25.0   85.0
1    Rafi   NaN   90.0
2  Nabila  23.0    NaN
3    Rafi   NaN   90.0

In [ ]:
#  Missing value check

print(df.isnull())
print(df.isnull().sum())  ## কোন column-এ কয়টা missing value

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False
Name     0
Age      2
Score    1
dtype: int64

In [ ]:
#Missing পূরণ করো (fillna)

df['Age'] = df['Age'].fillna(df['Age'].mean())

df['Score']= df['Score'].fillna(0)

df

     Name   Age  Score
0  Shanto  25.0   85.0
1    Rafi  24.0   90.0
2  Nabila  23.0    0.0
3    Rafi  24.0   90.0

In [ ]:
# find duplicate

print(df.duplicated())               # কোন row টা duplicate

df = df.drop_duplicates()           # duplicate row বাদ
df

0    False
1    False
2    False
3     True
dtype: bool

     Name   Age  Score
0  Shanto  25.0   85.0
1    Rafi  24.0   90.0
2  Nabila  23.0    0.0

In [ ]:
#  ডেটা টাইপ ঠিক করো:


df['Age'] = df['Age'].astype(int)
print(df.dtypes)

Name      object
Age        int64
Score    float64
dtype: object

/tmp/ipython-input-19-2215388361.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].astype(int)

In [ ]:
 # clean dataframe
print(df)

     Name  Age  Score
0  Shanto   25   85.0
1    Rafi   24   90.0
2  Nabila   23    0.0

**Data Manipulation in pandas**
 কিভাবে ডেটাকে সাজানো, গ্রুপ করা ও বিশ্লেষণ করা যায়।

In [ ]:
import pandas as pd

data = {
    'Name': ['Shanto', 'Rafi', 'Nabila', 'Asif', 'Tania'],
    'Dept': ['SWE', 'SWE', 'BBA', 'BBA', 'SWE'],
    'Score': [85, 90, 88, 82, 92]
}

df = pd.DataFrame(data)
df

     Name Dept  Score
0  Shanto  SWE     85
1    Rafi  SWE     90
2  Nabila  BBA     88
3    Asif  BBA     82
4   Tania  SWE     92

In [ ]:
# Data Sorting:

# Score অনুসারে বড় থেকে ছোট (descending):

sorted_df = df.sort_values(by='Score', ascending=False)
print(sorted_df)
print('................................')
# Score অনুসারে ছোট থেকে বড় (ascending):
sorted_df = df.sort_values(by='Score', ascending=True)
print(sorted_df)

     Name Dept  Score
4   Tania  SWE     92
1    Rafi  SWE     90
2  Nabila  BBA     88
0  Shanto  SWE     85
3    Asif  BBA     82
................................
     Name Dept  Score
3    Asif  BBA     82
0  Shanto  SWE     85
2  Nabila  BBA     88
1    Rafi  SWE     90
4   Tania  SWE     92

In [ ]:
#নাম অনুযায়ী (A-Z):


print(df.sort_values(by='Name'))

     Name Dept  Score
3    Asif  BBA     82
2  Nabila  BBA     88
1    Rafi  SWE     90
0  Shanto  SWE     85
4   Tania  SWE     92

Grouping & Aggregation:

In [ ]:
# প্রতিটি Dept-এর মোট Score:


print(df.groupby('Dept')['Score'].sum())

 #প্রতিটি Dept-এর গড় স্কোর:
print(df.groupby('Dept')['Score'].mean())

Dept
BBA    170
SWE    267
Name: Score, dtype: int64
Dept
BBA    85.0
SWE    89.0
Name: Score, dtype: float64

In [ ]:
#প্রতিটি Dept-এ কয়জন ছাত্র আছে:


print(df['Dept'].value_counts())
# অথবা
print(df.groupby('Dept')['Name'].count())

Dept
SWE    3
BBA    2
Name: count, dtype: int64
Dept
BBA    2
SWE    3
Name: Name, dtype: int64

In [ ]:
#কোন Dept-এ সবচেয়ে বেশি ছাত্র আছে?


dept_count = df['Dept'].value_counts()
print(" Number of Students per Dept:\n", dept_count)

# সবচেয়ে বেশি ছাত্র কোন Dept-এ
most_students_dept = dept_count.idxmax()
print('সবচেয়ে বেশি ছাত্র ',most_students_dept, ' Dept-এ থাকে')

 Number of Students per Dept:
 Dept
SWE    3
BBA    2
Name: count, dtype: int64
সবচেয়ে বেশি ছাত্র  SWE  Dept-এ থাকে

In [ ]:
import pandas as pd

data = {
    'Name': ['Shanto', 'Rafi', 'Nabila', 'Asif', 'Tania'],
    'Dept': ['SWE', 'SWE', 'BBA', 'BBA', 'SWE'],
    'Score1': [85, 90, 88, 82, 92],
    'Score2': [80, 91, 85, 79, 95]
}

df = pd.DataFrame(data)
df

     Name Dept  Score1  Score2
0  Shanto  SWE      85      80
1    Rafi  SWE      90      91
2  Nabila  BBA      88      85
3    Asif  BBA      82      79
4   Tania  SWE      92      95

In [ ]:
df_sorted = df.sort_values(by='Score1', ascending=False)
print(df_sorted)

     Name Dept  Score1  Score2
4   Tania  SWE      92      95
1    Rafi  SWE      90      91
2  Nabila  BBA      88      85
0  Shanto  SWE      85      80
3    Asif  BBA      82      79

In [ ]:
df_sorted = df.sort_values(by='Score2', ascending=False)
print(df_sorted)

     Name Dept  Score1  Score2
4   Tania  SWE      92      95
1    Rafi  SWE      90      91
2  Nabila  BBA      88      85
0  Shanto  SWE      85      80
3    Asif  BBA      82      79

In [ ]:
#Dept অনুযায়ী গ্রুপ করে প্রতিটি বিভাগের সব স্কোর দেখাও:

grouped = df.groupby('Dept')
print(grouped[['Score1', 'Score2']].mean())

      Score1     Score2
Dept
BBA     85.0  82.000000
SWE     89.0  88.666667

In [ ]:
 #Aggregation

 # প্রতিটি বিভাগের মধ্যে:গড় স্কোর,সর্বোচ্চ স্কোর,মোট ছাত্র সংখ্যা


agg_result = df.groupby('Dept').agg({
    'Score1': ['mean', 'max'],
    'Name': 'count'
})

print(agg_result)

     Score1      Name
       mean max count
Dept
BBA    85.0  88     2
SWE    89.0  92     3

In [ ]:
#নতুন Column তৈরি

#Score1 ও Score2 এর গড় নিয়ে Average column তৈরি করো:

df['Average'] = (df['Score1'] + df['Score2']) / 2
print(df)

     Name Dept  Score1  Score2  Average
0  Shanto  SWE      85      80     82.5
1    Rafi  SWE      90      91     90.5
2  Nabila  BBA      88      85     86.5
3    Asif  BBA      82      79     80.5
4   Tania  SWE      92      95     93.5

In [ ]:
#Grade Column তৈরি করো:

def assign_grade(avg):
    if avg >= 90:
        return 'A+'
    elif avg >= 80:
        return 'A'
    else:
        return 'B'

df['Grade'] = df['Average'].apply(assign_grade)
print(df)

     Name Dept  Score1  Score2  Average Grade
0  Shanto  SWE      85      80     82.5     A
1    Rafi  SWE      90      91     90.5    A+
2  Nabila  BBA      88      85     86.5     A
3    Asif  BBA      82      79     80.5     A
4   Tania  SWE      92      95     93.5    A+

**Merging & Joining in pandas**

pandas-এ তিনটি প্রধান উপায় আছে DataFrame একত্র করার:

Concatenate	pd.concat()	একের পর এক যোগ করা (row/column-wise)
Merge	pd.merge()	SQL-style অনুযায়ী একাধিক DataFrame যুক্ত করা
Join	df.join()	index বা কলাম অনুযায়ী যুক্ত করা

In [ ]:
#. pd.concat() → একসাথে যোগ করা

# Example: Row-wise concatenate

import pandas as pd

df1 = pd.DataFrame({
    'Name': ['Shanto', 'Rafi'],
    'Dept': ['SWE', 'SWE']
})

df2= pd.DataFrame({
    'Name' : ['Shawon','Hasib'],
    'Dept' : ['BBA','BBA']
})


result = pd.concat([df1, df2])
print(result)

     Name Dept
0  Shanto  SWE
1    Rafi  SWE
0  Shawon  BBA
1   Hasib  BBA

In [ ]:
# Column-wise concat:

df3 = pd.DataFrame({
    'Name': ['Shanto', 'Rafi'],
    'Score': [85, 90]
})

df4 = pd.DataFrame({
    'Grade': ['A', 'A+']
})

combined = pd.concat([df3, df4],axis=1)
print(combined)

     Name  Score Grade
0  Shanto     85     A
1    Rafi     90    A+

In [ ]:
 #pd.merge() → SQL-style Merge

#Example: Merge on common column (like foreign key)


students = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Shanto', 'Rafi', 'Tania']
})

scores = pd.DataFrame({
    'ID': [1, 2, 3],
    'Score': [85, 90, 92]
})

grade=pd.DataFrame({
    'ID':[1, 2, 3],
    'Grade':['A','A+','A+']
})



merged = pd.merge(students, scores, on='ID')
print(merged)

   ID    Name  Score
0   1  Shanto     85
1   2    Rafi     90
2   3   Tania     92

In [ ]:
#Merge with different types (left, right, outer, inner):


# inner merge (default): শুধু common ID
pd.merge(students, scores, on='ID', how='inner')

   ID    Name  Score
0   1  Shanto     85
1   2    Rafi     90
2   3   Tania     92

In [ ]:
# left join: students-এর সব data রাখবে
pd.merge(students, scores, on='ID', how='left')

   ID    Name  Score
0   1  Shanto     85
1   2    Rafi     90
2   3   Tania     92

In [ ]:
# df.join() → Index অনুযায়ী একত্র


df_a = pd.DataFrame({
    'Name': ['Santo', 'Rafi'],
    'Score': [85, 90]
}, index=['a', 'b'])

df_b = pd.DataFrame({
    'Grade': ['A', 'A+']
}, index=['a', 'b'])

joined = df_a.join(df_b)
print(joined)

    Name  Score Grade
a  Santo     85     A
b   Rafi     90    A+

In [ ]:
import pandas as pd

# Define the DataFrame
data = {
    'Name': ['Shanto', 'Arif', 'Nadia'],
    'Age': [23, 25, 24],
    'Dept': ['SWE', 'EEE', 'BBA']
}

df=pd.DataFrame(data)

# Column ও Row Access
print(df['Name'])      # শুধুমাত্র Name কলাম
print("..............................")
print(df['Age'])
print("..............................")

print(df.loc[0])       # index দিয়ে row
print('...............................')
print(df.iloc[1])      # position দিয়ে row

0    Shanto
1      Arif
2     Nadia
Name: Name, dtype: object
..............................
0    23
1    25
2    24
Name: Age, dtype: int64
..............................
Name    Shanto
Age         23
Dept       SWE
Name: 0, dtype: object
...............................
Name    Arif
Age       25
Dept     EEE
Name: 1, dtype: object