<a href="https://colab.research.google.com/github/MdRufsan/Python-/blob/main/pandas/4_pandas2%26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas সিরিজ এবং ডেটাফ্রেমের মতো উচ্চ স্তরের ডেটা স্ট্রাকচার অফার করে যা পাইথনে ডেটা বিশ্লেষণকে সহজ করে তোলে। এই ডেটা স্ট্রাকচারগুলি ndarrays এর উপরে তৈরি। অতএব, তাদের মধ্যে বেশিরভাগ কার্যকারিতা একই রকম এবং আপনি ndarray, Series এবং DataFrame-এ একই ফাংশন ব্যবহার করতে পারেন।

In [ ]:
import numpy as np
import pandas as pd

একটি সিরিজ হল একটি এক-মাত্রিক অ্যারের মতো বস্তু যার মধ্যে মানগুলির একটি ক্রম (NumPy ধরণের অনুরূপ) এবং ডেটা লেবেলের একটি সম্পর্কিত অ্যারে থাকে, যাকে এর index বলা হয়।

In [ ]:
import pandas as pd
series1 = pd.Series([1,2,3,4,5,6])
series1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
series2 = pd.Series([12000, 17000, 1100], index=['January', 'February', 'October'])
series2

January     12000
February    17000
October      1100
dtype: int64

In [ ]:
series2.index

Index(['January', 'February', 'October'], dtype='object')

In [ ]:
# give index column name
series2.index.name = 'Month'
series2

Month
January     12000
February    17000
October      1100
dtype: int64

In [ ]:
series2.index = ['January', 'March', 'April']
series2

January    12000
March      17000
April       1100
dtype: int64

In [ ]:
monthly_income=pd.Series([20000, 17000, 11000], index=['May', 'June', 'July'])
monthly_income.index.name='Month'
monthly_income

Month
May     20000
June    17000
July    11000
dtype: int64

In [ ]:
monthly_income= pd.Series([20000, 17000, 11000], index=['May', 'June', 'July'])
monthly_income.index.name = 'Month'
display(monthly_income)

Month
May     20000
June    17000
July    11000
dtype: int64

We can also use a dictionary to create a Series.

In [ ]:
age={
    'Shanto' : 23,
    'Shawon' : 19,
    'Hasib'  : 10
}
age_series = pd.Series(age)

age_series

Shanto    23
Shawon    19
Hasib     10
dtype: int64

In [ ]:
age_series.name="Name & Age"
age_series.index.name="Name"
age_series

Name
Shanto    23
Shawon    19
Hasib     10
Name: Name & Age, dtype: int64

In [ ]:
age_series.values

array([23, 19, 10])

In [ ]:
age_series.index

Index(['Shanto', 'Shawon', 'Hasib'], dtype='object', name='Name')

**Indexing and Slicing**
We can use all the indexing and slicing mechanisms of Python and NumPy. In addition, we can use the Index of a Series to index or slice a Series.

In [ ]:
series2.index.name="Month"
print(series2)
series2.index

Month
January    12000
March      17000
April       1100
dtype: int64

Index(['January', 'March', 'April'], dtype='object', name='Month')

In [ ]:
series2['April']

np.int64(1100)

In [ ]:
series2[['April','March']]

Month
April     1100
March    17000
dtype: int64

In [ ]:
series2[2]

/tmp/ipython-input-194-1007643937.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series2[2]

np.int64(1100)

In [ ]:
series2[[0, 1]]

/tmp/ipython-input-195-1556155739.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series2[[0, 1]]

Month
January    12000
March      17000
dtype: int64

In [ ]:
series2[1:]

Month
March    17000
April     1100
dtype: int64

In [ ]:
series2 < 10000

Month
January    False
March      False
April       True
dtype: bool

In [ ]:
series2[series2 > 10000]

Month
January    12000
March      17000
dtype: int64

In [ ]:
se = pd.Series([1,10,1,4,5])
se

0     1
1    10
2     1
3     4
4     5
dtype: int64

In [ ]:
se>=10

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [ ]:
se[se > 2]

1    10
3     4
4     5
dtype: int64

**Null values **

In [ ]:

series4= pd.Series([10000,np.nan,20000,11000,np.nan],index=['a','b','c','d','e'])
series4

a    10000.0
b        NaN
c    20000.0
d    11000.0
e        NaN
dtype: float64

In [ ]:
series4.isnull()

a    False
b     True
c    False
d    False
e     True
dtype: bool

In [ ]:
series4[series4.isnull()]

b   NaN
e   NaN
dtype: float64

In [ ]:
series4[series4.notnull()]

a    10000.0
c    20000.0
d    11000.0
dtype: float64

In [ ]:
series4[series4.isnull()]="Missing value"
series4

/tmp/ipython-input-206-2554394201.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Missing value' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  series4[series4.isnull()]="Missing value"

a          10000.0
b    Missing value
c          20000.0
d          11000.0
e    Missing value
dtype: object

## DataFrame

You can think of it like a list of `Series`. This the main data structure for working with tabular data.

In [ ]:
dic = {
    'age': [21, 32, 33, 55],
    'height': [1, 6, 7, 3],
    'weight': [12, 34, 45, 67]
}
df=pd.DataFrame(dic)
df

   age  height  weight
0   21       1      12
1   32       6      34
2   33       7      45
3   55       3      67

We can access columns of a DataFrame by using dictionary like indexing. Notice that the index of the output Series is same as the DataFrame.

In [ ]:
df.age

0    21
1    32
2    33
3    55
Name: age, dtype: int64

In [ ]:
df[['age','height']]

   age  height
0   21       1
1   32       6
2   33       7
3   55       3

We can create and delete a new feature using dictionary like style.

In [ ]:
df['income'] = [145, 155, 167, 159]
df

   age  height  weight  income
0   21       1      12     145
1   32       6      34     155
2   33       7      45     167
3   55       3      67     159

In [ ]:
del df['height']
df

   age  weight  income
0   21      12     145
1   32      34     155
2   33      45     167
3   55      67     159

In [ ]:
#We can update the value of any specific cell in the DataFrame.
df["weight"][3] = 40
df

/tmp/ipython-input-219-674356505.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["weight"][3] = 40

   age  weight  income
0   21      12     145
1   32      40     155
2   33      45     167
3   55      40     159

**Indexing and Slicing**

In [ ]:
df[df ["income"] >150]

   age  weight  income
1   32      40     155
2   33      45     167
3   55      40     159

In [ ]:
df[(df['age'] >= 20) & (df['age'] <= 35)]

   age  weight  income
0   21      12     145
1   32      40     155
2   33      45     167

In [ ]:
df.loc[(df['age'] >= 20) & (df['age'] <= 35), ['age', 'income']]

   age  income
0   21     145
1   32     155
2   33     167

In [ ]:
df.loc[2]

age        33
weight     45
income    167
Name: 2, dtype: int64

In [ ]:
df_cleaned['DiscountedRevenue'] = (df_cleaned['Quantity'] * df_cleaned['UnitPrice']) * (1 - 0.1)

display(df_cleaned.head())

In [ ]:
overall_average_revenue = df_cleaned['TotalRevenue'].mean()
display(overall_average_revenue)